### ISSUE TITLE
Pas de licence

### ISSUE THREAD

**Issue by beuss** [franckverrot/codes-bic-france#2]
Bonjour,
Selon quelles conditions les données sont-elles utilisables ? D'où proviennent-elles ?
Cordialement,

**Comment by franckverrot** [comment]
Hello,

Je ne pense pas pouvoir apposer de licence car ces données (extraites de différentes sources sur le net ou via des extraits bancaires) sont librement consultables, et il serait fort difficile de la faire respecter.  A ma connaissance, seul site officiel du SWIFT pourrait fournir un extrait garanti exhaustif et récent.

**Comment by beuss** [comment]
Salut,
Pour ce qui est de la compilation de données que tu fournis, elle peut être librement intégrable dans n'importe quoi ?

**Comment by franckverrot** [comment]
Hello,

> elle peut être librement intégrable dans n'importe quoi ? 

Rien ne t'en empêche, c'est à tes risques et périls comme on dit 😅
