### ISSUE TITLE
Identifiant banque et agence

### ISSUE THREAD

**Issue by GuillaumeSorel** [franckverrot/codes-bic-france#4]
Franck, 
merci beaucoup pour ce gros boulot.
Pour ajouter cette liste à CiviCRM, j'ai besoin des identifiants de la banque et la succursale comme [dans cette référence](https://www.xe.com/ibancalculator/sample/?ibancountry=france).
Comment le retrouver ?
Guillaume

**Comment by franckverrot** [comment]
Hello, ravi que ça aide d'autres personnes :-)

Concernant ta question, ne suffit-il pas d'extraire ces identifiants de l'IBAN?
